let students=["suman","kisna","paras"];
console.log(students);
students.push("deepak");
console.log(students);
students.pop();
console.log(students);
students.shift();
console.log(students);
students.unshift("suman");
console.log(students);
let primary=["red","yellow","blue"];
let secondary=["orange","green","violet"];
console.log(primary);
console.log(secondary);
console.log(primary.concat(secondary));
console.log(primary);
primary.reverse();
console.log(primary);
console.log(primary.slice(1));
let colors=["red","yellow","blue","orange","pink","white"];
colors.splice(1,3);
console.log(colors);
colors.splice(1,0,"black","grey");
console.log(colors);
