let btn=document.createElement('button');
btn.innerText="Click me";
let body=document.querySelector('body');
body.append(btn);
let input=document.createElement('input');
body.append(input);
input.type='text';
input.placeholder='username';
btn.id='btn';
let button=document.querySelector('button');
button.style.color='white';
button.style.backgroundColor='blue';
let heading=document.createElement('h1');
heading.innerText="DOM Practice";
heading.style.color='purple';
heading.style.textDecoration='underline';
body.append(heading);
let para=document.createElement('p');
para.innerHTML="Apna College <b>Delta</b> Practice";
body.prepend(para);